name: build-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: install dependencies
          run: sudo ./install-dependencies.sh

        - name: build & test
          run: ./build.sh