# Copyright 2020 Vectorized, Inc.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.md
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0

name: build-test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04

    steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: update container base
          run: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update -y
            apt-get install -y git sudo pkg-config

        - name: install dependencies
          run: |
            ./install-dependencies.sh
            apt-get install -y gcc-10 g++-10
            update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10 --slave /usr/bin/g++ g++ /usr/bin/g++-10

        - name: build & test
          run: ./build.sh -DCMAKE_UNITY_BUILD=ON
