name: Go

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v ./...
      working-directory: src/go/rpk/

    - name: Build
      run: go build -o rpk -v ./...
      working-directory: src/go/rpk/

    - name: Publish
      run: echo "TODO"
